from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from dateutil.parser import isoparse

from ..models.certificate_type import CertificateType
from ..types import UNSET, Unset

T = TypeVar("T", bound="CertificateInfo")


@_attrs_define
class CertificateInfo:
    """
    Attributes:
        key_size (int | Unset): Certificate key length (in bits).
        key_algorithm (None | str | Unset): Certificate encryption algorithm.
        thumb_print (None | str | Unset): Thumbprint uniquely identifying a certificate.
        serial_number (None | str | Unset): Serial number of the certificate.
        type_ (CertificateType | Unset): Type of the certificate.
        issued_by (None | str | Unset): Entity that issued the certificate.
        issued_to (None | str | Unset): Entity to which the certificate is issued.
        subject (None | str | Unset): Name of a subject to which the certificate belongs.
        expiration_date_utc (datetime.datetime | Unset): Date and time when the certificate expires.
        is_auto_generated (bool | Unset): Defines whether the certificate was generated automatically.
    """

    key_size: int | Unset = UNSET
    key_algorithm: None | str | Unset = UNSET
    thumb_print: None | str | Unset = UNSET
    serial_number: None | str | Unset = UNSET
    type_: CertificateType | Unset = UNSET
    issued_by: None | str | Unset = UNSET
    issued_to: None | str | Unset = UNSET
    subject: None | str | Unset = UNSET
    expiration_date_utc: datetime.datetime | Unset = UNSET
    is_auto_generated: bool | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        key_size = self.key_size

        key_algorithm: None | str | Unset
        if isinstance(self.key_algorithm, Unset):
            key_algorithm = UNSET
        else:
            key_algorithm = self.key_algorithm

        thumb_print: None | str | Unset
        if isinstance(self.thumb_print, Unset):
            thumb_print = UNSET
        else:
            thumb_print = self.thumb_print

        serial_number: None | str | Unset
        if isinstance(self.serial_number, Unset):
            serial_number = UNSET
        else:
            serial_number = self.serial_number

        type_: str | Unset = UNSET
        if not isinstance(self.type_, Unset):
            type_ = self.type_.value

        issued_by: None | str | Unset
        if isinstance(self.issued_by, Unset):
            issued_by = UNSET
        else:
            issued_by = self.issued_by

        issued_to: None | str | Unset
        if isinstance(self.issued_to, Unset):
            issued_to = UNSET
        else:
            issued_to = self.issued_to

        subject: None | str | Unset
        if isinstance(self.subject, Unset):
            subject = UNSET
        else:
            subject = self.subject

        expiration_date_utc: str | Unset = UNSET
        if not isinstance(self.expiration_date_utc, Unset):
            expiration_date_utc = self.expiration_date_utc.isoformat()

        is_auto_generated = self.is_auto_generated

        field_dict: dict[str, Any] = {}

        field_dict.update({})
        if key_size is not UNSET:
            field_dict["keySize"] = key_size
        if key_algorithm is not UNSET:
            field_dict["keyAlgorithm"] = key_algorithm
        if thumb_print is not UNSET:
            field_dict["thumbPrint"] = thumb_print
        if serial_number is not UNSET:
            field_dict["serialNumber"] = serial_number
        if type_ is not UNSET:
            field_dict["type"] = type_
        if issued_by is not UNSET:
            field_dict["issuedBy"] = issued_by
        if issued_to is not UNSET:
            field_dict["issuedTo"] = issued_to
        if subject is not UNSET:
            field_dict["subject"] = subject
        if expiration_date_utc is not UNSET:
            field_dict["expirationDateUtc"] = expiration_date_utc
        if is_auto_generated is not UNSET:
            field_dict["isAutoGenerated"] = is_auto_generated

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        key_size = d.pop("keySize", UNSET)

        def _parse_key_algorithm(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        key_algorithm = _parse_key_algorithm(d.pop("keyAlgorithm", UNSET))

        def _parse_thumb_print(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        thumb_print = _parse_thumb_print(d.pop("thumbPrint", UNSET))

        def _parse_serial_number(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        serial_number = _parse_serial_number(d.pop("serialNumber", UNSET))

        _type_ = d.pop("type", UNSET)
        type_: CertificateType | Unset
        if isinstance(_type_, Unset):
            type_ = UNSET
        else:
            type_ = CertificateType(_type_)

        def _parse_issued_by(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        issued_by = _parse_issued_by(d.pop("issuedBy", UNSET))

        def _parse_issued_to(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        issued_to = _parse_issued_to(d.pop("issuedTo", UNSET))

        def _parse_subject(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        subject = _parse_subject(d.pop("subject", UNSET))

        _expiration_date_utc = d.pop("expirationDateUtc", UNSET)
        expiration_date_utc: datetime.datetime | Unset
        if isinstance(_expiration_date_utc, Unset):
            expiration_date_utc = UNSET
        else:
            expiration_date_utc = isoparse(_expiration_date_utc)

        is_auto_generated = d.pop("isAutoGenerated", UNSET)

        certificate_info = cls(
            key_size=key_size,
            key_algorithm=key_algorithm,
            thumb_print=thumb_print,
            serial_number=serial_number,
            type_=type_,
            issued_by=issued_by,
            issued_to=issued_to,
            subject=subject,
            expiration_date_utc=expiration_date_utc,
            is_auto_generated=is_auto_generated,
        )

        return certificate_info
