from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.problem_details_400_errors_type_0 import ProblemDetails400ErrorsType0


T = TypeVar("T", bound="ProblemDetails400")


@_attrs_define
class ProblemDetails400:
    """
    Attributes:
        detail (None | str | Unset): Detailed description of the error.
        errors (None | ProblemDetails400ErrorsType0 | Unset): The error code is a string that uniquely identifies an
            error and must be understood by programs that detect error types.
        status (int | Unset): HTTP status code of the error generated by the origin server.
        title (None | str | Unset): Short summary of the error.
        trace_id (None | str | Unset): Unique identifier which can be used to search logs for more details.
        type_ (None | str | Unset): Type of the error.
    """

    detail: None | str | Unset = UNSET
    errors: None | ProblemDetails400ErrorsType0 | Unset = UNSET
    status: int | Unset = UNSET
    title: None | str | Unset = UNSET
    trace_id: None | str | Unset = UNSET
    type_: None | str | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        from ..models.problem_details_400_errors_type_0 import ProblemDetails400ErrorsType0

        detail: None | str | Unset
        if isinstance(self.detail, Unset):
            detail = UNSET
        else:
            detail = self.detail

        errors: dict[str, Any] | None | Unset
        if isinstance(self.errors, Unset):
            errors = UNSET
        elif isinstance(self.errors, ProblemDetails400ErrorsType0):
            errors = self.errors.to_dict()
        else:
            errors = self.errors

        status = self.status

        title: None | str | Unset
        if isinstance(self.title, Unset):
            title = UNSET
        else:
            title = self.title

        trace_id: None | str | Unset
        if isinstance(self.trace_id, Unset):
            trace_id = UNSET
        else:
            trace_id = self.trace_id

        type_: None | str | Unset
        if isinstance(self.type_, Unset):
            type_ = UNSET
        else:
            type_ = self.type_

        field_dict: dict[str, Any] = {}

        field_dict.update({})
        if detail is not UNSET:
            field_dict["detail"] = detail
        if errors is not UNSET:
            field_dict["errors"] = errors
        if status is not UNSET:
            field_dict["status"] = status
        if title is not UNSET:
            field_dict["title"] = title
        if trace_id is not UNSET:
            field_dict["traceId"] = trace_id
        if type_ is not UNSET:
            field_dict["type"] = type_

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.problem_details_400_errors_type_0 import ProblemDetails400ErrorsType0

        d = dict(src_dict)

        def _parse_detail(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        detail = _parse_detail(d.pop("detail", UNSET))

        def _parse_errors(data: object) -> None | ProblemDetails400ErrorsType0 | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                errors_type_0 = ProblemDetails400ErrorsType0.from_dict(data)

                return errors_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | ProblemDetails400ErrorsType0 | Unset, data)

        errors = _parse_errors(d.pop("errors", UNSET))

        status = d.pop("status", UNSET)

        def _parse_title(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        title = _parse_title(d.pop("title", UNSET))

        def _parse_trace_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        trace_id = _parse_trace_id(d.pop("traceId", UNSET))

        def _parse_type_(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        type_ = _parse_type_(d.pop("type", UNSET))

        problem_details_400 = cls(
            detail=detail,
            errors=errors,
            status=status,
            title=title,
            trace_id=trace_id,
            type_=type_,
        )

        return problem_details_400
