from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.problem_details_401_extensions_type_0 import ProblemDetails401ExtensionsType0


T = TypeVar("T", bound="ProblemDetails401")


@_attrs_define
class ProblemDetails401:
    """
    Attributes:
        extensions (None | ProblemDetails401ExtensionsType0 | Unset): Additional information on the error.
        status (int | Unset): HTTP status code of the error generated by the origin server.
        title (None | str | Unset): Short summary of the error.
        detail (None | str | Unset): Detailed description of the error.
        type_ (None | str | Unset): Type of the error.
    """

    extensions: None | ProblemDetails401ExtensionsType0 | Unset = UNSET
    status: int | Unset = UNSET
    title: None | str | Unset = UNSET
    detail: None | str | Unset = UNSET
    type_: None | str | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        from ..models.problem_details_401_extensions_type_0 import ProblemDetails401ExtensionsType0

        extensions: dict[str, Any] | None | Unset
        if isinstance(self.extensions, Unset):
            extensions = UNSET
        elif isinstance(self.extensions, ProblemDetails401ExtensionsType0):
            extensions = self.extensions.to_dict()
        else:
            extensions = self.extensions

        status = self.status

        title: None | str | Unset
        if isinstance(self.title, Unset):
            title = UNSET
        else:
            title = self.title

        detail: None | str | Unset
        if isinstance(self.detail, Unset):
            detail = UNSET
        else:
            detail = self.detail

        type_: None | str | Unset
        if isinstance(self.type_, Unset):
            type_ = UNSET
        else:
            type_ = self.type_

        field_dict: dict[str, Any] = {}

        field_dict.update({})
        if extensions is not UNSET:
            field_dict["extensions"] = extensions
        if status is not UNSET:
            field_dict["status"] = status
        if title is not UNSET:
            field_dict["title"] = title
        if detail is not UNSET:
            field_dict["detail"] = detail
        if type_ is not UNSET:
            field_dict["type"] = type_

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.problem_details_401_extensions_type_0 import ProblemDetails401ExtensionsType0

        d = dict(src_dict)

        def _parse_extensions(data: object) -> None | ProblemDetails401ExtensionsType0 | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                extensions_type_0 = ProblemDetails401ExtensionsType0.from_dict(data)

                return extensions_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | ProblemDetails401ExtensionsType0 | Unset, data)

        extensions = _parse_extensions(d.pop("extensions", UNSET))

        status = d.pop("status", UNSET)

        def _parse_title(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        title = _parse_title(d.pop("title", UNSET))

        def _parse_detail(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        detail = _parse_detail(d.pop("detail", UNSET))

        def _parse_type_(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        type_ = _parse_type_(d.pop("type", UNSET))

        problem_details_401 = cls(
            extensions=extensions,
            status=status,
            title=title,
            detail=detail,
            type_=type_,
        )

        return problem_details_401
