from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.problem_details_extensions_type_0 import ProblemDetailsExtensionsType0


T = TypeVar("T", bound="ProblemDetails")


@_attrs_define
class ProblemDetails:
    r"""\[Applies only if the session completes with an error] Information on the error.

    Attributes:
        type_ (None | str | Unset): Type of the error.
        title (None | str | Unset): Short summary of the error.
        status (int | None | Unset): HTTP status code of the error generated by the origin server.
        detail (None | str | Unset): Detailed description of the error.
        instance (None | str | Unset): System ID assigned to an instance in the Veeam Backup for Microsoft Azure REST
            API where the error occurred.
        extensions (None | ProblemDetailsExtensionsType0 | Unset): Additional information on the error.
    """

    type_: None | str | Unset = UNSET
    title: None | str | Unset = UNSET
    status: int | None | Unset = UNSET
    detail: None | str | Unset = UNSET
    instance: None | str | Unset = UNSET
    extensions: None | ProblemDetailsExtensionsType0 | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        from ..models.problem_details_extensions_type_0 import ProblemDetailsExtensionsType0

        type_: None | str | Unset
        if isinstance(self.type_, Unset):
            type_ = UNSET
        else:
            type_ = self.type_

        title: None | str | Unset
        if isinstance(self.title, Unset):
            title = UNSET
        else:
            title = self.title

        status: int | None | Unset
        if isinstance(self.status, Unset):
            status = UNSET
        else:
            status = self.status

        detail: None | str | Unset
        if isinstance(self.detail, Unset):
            detail = UNSET
        else:
            detail = self.detail

        instance: None | str | Unset
        if isinstance(self.instance, Unset):
            instance = UNSET
        else:
            instance = self.instance

        extensions: dict[str, Any] | None | Unset
        if isinstance(self.extensions, Unset):
            extensions = UNSET
        elif isinstance(self.extensions, ProblemDetailsExtensionsType0):
            extensions = self.extensions.to_dict()
        else:
            extensions = self.extensions

        field_dict: dict[str, Any] = {}

        field_dict.update({})
        if type_ is not UNSET:
            field_dict["type"] = type_
        if title is not UNSET:
            field_dict["title"] = title
        if status is not UNSET:
            field_dict["status"] = status
        if detail is not UNSET:
            field_dict["detail"] = detail
        if instance is not UNSET:
            field_dict["instance"] = instance
        if extensions is not UNSET:
            field_dict["extensions"] = extensions

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.problem_details_extensions_type_0 import ProblemDetailsExtensionsType0

        d = dict(src_dict)

        def _parse_type_(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        type_ = _parse_type_(d.pop("type", UNSET))

        def _parse_title(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        title = _parse_title(d.pop("title", UNSET))

        def _parse_status(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        status = _parse_status(d.pop("status", UNSET))

        def _parse_detail(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        detail = _parse_detail(d.pop("detail", UNSET))

        def _parse_instance(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        instance = _parse_instance(d.pop("instance", UNSET))

        def _parse_extensions(data: object) -> None | ProblemDetailsExtensionsType0 | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                extensions_type_0 = ProblemDetailsExtensionsType0.from_dict(data)

                return extensions_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | ProblemDetailsExtensionsType0 | Unset, data)

        extensions = _parse_extensions(d.pop("extensions", UNSET))

        problem_details = cls(
            type_=type_,
            title=title,
            status=status,
            detail=detail,
            instance=instance,
            extensions=extensions,
        )

        return problem_details
