from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.problem_details_403_extensions_type_0 import ProblemDetails403ExtensionsType0


T = TypeVar("T", bound="ProblemDetails403")


@_attrs_define
class ProblemDetails403:
    """
    Attributes:
        extensions (None | ProblemDetails403ExtensionsType0 | Unset): Additional information on the error.
        status (int | Unset): HTTP status code of the error generated by the origin server.
        title (None | str | Unset): Short summary of the error.
        type_ (None | str | Unset): Type of the error.
        license_agreement_acceptance_required (bool | None | Unset): Defines whether a license agreement is accepted.
    """

    extensions: None | ProblemDetails403ExtensionsType0 | Unset = UNSET
    status: int | Unset = UNSET
    title: None | str | Unset = UNSET
    type_: None | str | Unset = UNSET
    license_agreement_acceptance_required: bool | None | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        from ..models.problem_details_403_extensions_type_0 import ProblemDetails403ExtensionsType0

        extensions: dict[str, Any] | None | Unset
        if isinstance(self.extensions, Unset):
            extensions = UNSET
        elif isinstance(self.extensions, ProblemDetails403ExtensionsType0):
            extensions = self.extensions.to_dict()
        else:
            extensions = self.extensions

        status = self.status

        title: None | str | Unset
        if isinstance(self.title, Unset):
            title = UNSET
        else:
            title = self.title

        type_: None | str | Unset
        if isinstance(self.type_, Unset):
            type_ = UNSET
        else:
            type_ = self.type_

        license_agreement_acceptance_required: bool | None | Unset
        if isinstance(self.license_agreement_acceptance_required, Unset):
            license_agreement_acceptance_required = UNSET
        else:
            license_agreement_acceptance_required = self.license_agreement_acceptance_required

        field_dict: dict[str, Any] = {}

        field_dict.update({})
        if extensions is not UNSET:
            field_dict["extensions"] = extensions
        if status is not UNSET:
            field_dict["status"] = status
        if title is not UNSET:
            field_dict["title"] = title
        if type_ is not UNSET:
            field_dict["type"] = type_
        if license_agreement_acceptance_required is not UNSET:
            field_dict["licenseAgreementAcceptanceRequired"] = license_agreement_acceptance_required

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.problem_details_403_extensions_type_0 import ProblemDetails403ExtensionsType0

        d = dict(src_dict)

        def _parse_extensions(data: object) -> None | ProblemDetails403ExtensionsType0 | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                extensions_type_0 = ProblemDetails403ExtensionsType0.from_dict(data)

                return extensions_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | ProblemDetails403ExtensionsType0 | Unset, data)

        extensions = _parse_extensions(d.pop("extensions", UNSET))

        status = d.pop("status", UNSET)

        def _parse_title(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        title = _parse_title(d.pop("title", UNSET))

        def _parse_type_(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        type_ = _parse_type_(d.pop("type", UNSET))

        def _parse_license_agreement_acceptance_required(data: object) -> bool | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(bool | None | Unset, data)

        license_agreement_acceptance_required = _parse_license_agreement_acceptance_required(
            d.pop("licenseAgreementAcceptanceRequired", UNSET)
        )

        problem_details_403 = cls(
            extensions=extensions,
            status=status,
            title=title,
            type_=type_,
            license_agreement_acceptance_required=license_agreement_acceptance_required,
        )

        return problem_details_403
