from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

T = TypeVar("T", bound="UserMfaAccept")


@_attrs_define
class UserMfaAccept:
    """
    Attributes:
        code (str): Specifies the six-digit verification code generated by an authenticator application on the trusted
            device.
        token (str): Specifies the token previously received from the authorization server.
    """

    code: str
    token: str

    def to_dict(self) -> dict[str, Any]:
        code = self.code

        token = self.token

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "code": code,
                "token": token,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        code = d.pop("code")

        token = d.pop("token")

        user_mfa_accept = cls(
            code=code,
            token=token,
        )

        return user_mfa_accept
