from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

T = TypeVar("T", bound="VeeamVaultRegistrationRequest")


@_attrs_define
class VeeamVaultRegistrationRequest:
    """
    Attributes:
        token (str): Specifies a token generated by Veeam Backup for Microsoft Azure that you can use to register your
            backup appliance in Veeam Data Cloud Vault.
    """

    token: str

    def to_dict(self) -> dict[str, Any]:
        token = self.token

        field_dict: dict[str, Any] = {}

        field_dict.update(
            {
                "token": token,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        token = d.pop("token")

        veeam_vault_registration_request = cls(
            token=token,
        )

        return veeam_vault_registration_request
