import importlib
from datetime import datetime, timedelta, timezone
from typing import Any

# ----------------------------
# API namespace proxy
# ----------------------------


class ApiNamespace:
    """
    Lazy namespace for openapi-python-client operation modules.

    Example:
        vc.api("virtual_machines").get_all_virtual_machines
        → veeam_az.v8_1.api.virtual_machines.get_all_virtual_machines.asyncio
    """

    def __init__(self, client: "VeeamClient", base_module: str):
        self._client = client
        self._base = base_module

    def __getattr__(self, name: str):
        mod = importlib.import_module(f"{self._base}.{name}")
        return mod.asyncio


# ----------------------------
# main client
# ----------------------------


class VeeamClient:
    """
    Shared async client for versioned openapi-python-client SDKs.

    Responsibilities:
    - version routing
    - authentication (username/password or token)
    - token refresh (for password-based auth)
    - API namespace routing
    """

    def __init__(
        self,
        host: str,
        api_version: str,
        verify_ssl: bool = True,
        username: str | None = None,
        password: str | None = None,
        token: str | None = None,
    ):
        self.host = self._normalize_host(host)
        self.api_version = api_version
        self.verify_ssl = verify_ssl

        # Support either username/password OR a pre-existing token
        if token:
            self.token = token
            self.username = None
            self.password = None
        elif username and password:
            self.username = username
            self.password = password
            self.token = None
        else:
            raise ValueError(
                "Must provide either 'token' or both 'username' and 'password'"
            )

        from .versions import VERSION_TO_PACKAGE

        if api_version not in VERSION_TO_PACKAGE:
            raise ValueError(f"Unsupported API version: {api_version}")

        self.package = VERSION_TO_PACKAGE[api_version]

        self._client = None
        self._access_token = None
        self._refresh_token = None
        self._expires_at: datetime | None = None

    @staticmethod
    def _normalize_host(host: str) -> str:
        """Strip trailing slashes and any /api(/v8.1) suffix.

        Endpoint paths generated by openapi-python-client already include the
        full ``/api/...`` prefix, so the base URL must be the bare host.
        """
        cleaned = host.rstrip("/")
        for suffix in ("/api/v8.1", "/api"):
            if cleaned.endswith(suffix):
                cleaned = cleaned[: -len(suffix)]
        return cleaned.rstrip("/")

    # ----------------------------
    # connection + auth
    # ----------------------------

    async def connect(self):
        AuthenticatedClient = getattr(
            importlib.import_module(f"{self.package}.client"), "AuthenticatedClient"
        )

        # If using a pre-existing token, skip authentication
        if self.token:
            self._access_token = self.token
            self._client = AuthenticatedClient(
                base_url=self.host,
                token=self._access_token,
                verify_ssl=self.verify_ssl,
            )
            return

        # Otherwise, authenticate with username/password
        token = await self._issue_token(grant="password")
        self._store_token(token, AuthenticatedClient)

    async def close(self):
        # openapi-python-client has no shared session to close
        pass

    # ----------------------------
    # token handling
    # ----------------------------

    async def _issue_token(self, grant: str, client=None):
        """Call the ``/api/oauth2/token`` endpoint with a password or refresh grant."""
        Client = getattr(importlib.import_module(f"{self.package}.client"), "Client")
        login_authenticate = importlib.import_module(
            f"{self.package}.api.login.login_authenticate"
        )
        LoginFromClient = getattr(
            importlib.import_module(f"{self.package}.models.login_from_client"),
            "LoginFromClient",
        )
        GrantType = getattr(
            importlib.import_module(f"{self.package}.models.grant_type"),
            "GrantType",
        )

        if grant == "password":
            body = LoginFromClient(
                grant_type=GrantType.PASSWORD,
                username=self.username,
                password=self.password,
            )
        elif grant == "refresh_token":
            body = LoginFromClient(
                grant_type=GrantType.REFRESH_TOKEN,
                refresh_token=self._refresh_token,
            )
        else:
            raise ValueError(f"Unsupported grant type: {grant}")

        if client is None:
            client = self._client or Client(
                base_url=self.host,
                verify_ssl=self.verify_ssl,
            )

        return await login_authenticate.asyncio(client=client, body=body)

    def _store_token(self, token, AuthenticatedClient):
        self._access_token = token.access_token
        self._refresh_token = token.refresh_token
        self._expires_at = datetime.now(timezone.utc) + timedelta(
            seconds=token.expires_in - 30
        )

        self._client = AuthenticatedClient(
            base_url=self.host,
            token=self._access_token,
            verify_ssl=self.verify_ssl,
        )

    async def _refresh_token_if_needed(self):
        # Skip refresh for permanent tokens
        if self.token:
            return

        if self._expires_at and datetime.now(timezone.utc) < self._expires_at:
            return

        Client = getattr(importlib.import_module(f"{self.package}.client"), "Client")
        AuthenticatedClient = getattr(
            importlib.import_module(f"{self.package}.client"), "AuthenticatedClient"
        )

        # Try the refresh grant first, fall back to password re-authentication.
        try:
            token = await self._issue_token(grant="refresh_token")
        except Exception as e:
            if not self.username or not self.password:
                raise RuntimeError(
                    "Token refresh failed and no username/password available "
                    "for re-authentication"
                ) from e
            tmp = Client(base_url=self.host, verify_ssl=self.verify_ssl)
            token = await self._issue_token(grant="password", client=tmp)

        self._store_token(token, AuthenticatedClient)

    # ----------------------------
    # API access
    # ----------------------------

    def api(self, name: str) -> Any:
        """
        Smart API accessor.

        Examples:
            vc.api("virtual_machines").get_all_virtual_machines
            vc.api("virtual_machines.get_all_virtual_machines")
        """

        # direct operation
        if "." in name:
            mod = importlib.import_module(f"{self.package}.api.{name}")
            return mod.asyncio

        # namespace
        return ApiNamespace(self, f"{self.package}.api.{name}")

    async def call(self, fn, *args, **kwargs):
        """
        Wrap any API call with automatic token refresh.
        """
        await self._refresh_token_if_needed()

        return await fn(client=self._client, *args, **kwargs)
